/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Honma (https://sketchfab.com/sekizo)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/wood-carved-bear-d72978ac57d2494788dcdc7037496b14
Title: Wood-carved bear
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bear(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-2, 3.4, 0.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Model_material0_0.geometry}
          material={materials.material0}
          rotation={[0, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')