/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
// import React, { useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { gsap } from 'gsap';


export default function OtherShell({ refShell1, refShell2, refShell3, refShell4, refShell5, refShell6, shellsGroupRef, ...props }) {
  const { nodes, materials } = useGLTF('/sea_shell_2.glb')


  // Verweise auf die Muscheln, die aus den Props kommen
  const shell1Ref = refShell1 || useRef(null);
  const shell2Ref = refShell2 || useRef(null);
  const shell3Ref = refShell3 || useRef(null);
  const shell4Ref = refShell4 || useRef(null);
  const shell5Ref = refShell5 || useRef(null);
  const shell6Ref = refShell6 || useRef(null);


//   useEffect(() => {
//     // GSAP Animation für kontinuierliche Drehung der Muscheln
//     if (shellsGroupRef.current) {

      
//       console.log("Aktuelle Position der Gruppe:", shellsGroupRef.current.position);

//       // Stelle sicher, dass die Gruppe richtig positioniert ist, z.B.:
      

//       gsap.to(shellsGroupRef.current.rotation, {
//         y: "+=6.28",     // Eine komplette Umdrehung (2 * Pi)
//         duration: 30,
//         repeat: -1,
//         ease: "linear",
//       });

      
//     }
//   }, [shellsGroupRef]);


useEffect(() => {
    if (shellsGroupRef.current) {
      // GSAP-Animation: kontinuierliche Rotation
      gsap.to(shellsGroupRef.current.rotation, {
        y: Math.PI * 2, // Eine volle Drehung
        duration: 30,    // Dauer der Animation in Sekunden
        repeat: -1,     // Unendliche Wiederholung
        ease: 'linear', // Gleichmäßige Bewegung
      });
    }
  }, [shellsGroupRef]);



  return (
    <group {...props} dispose={null} ref={shellsGroupRef} scale={[3, 3, 3]}>
        <group ref={shell1Ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2002.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3002.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4002.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5002.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6002.geometry}
        material={materials.Muschel_Material_u1_v1}
      />

</group>

<group ref={shell2Ref}>



      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Muschel_Material_u1_v1}
      />

</group>
<group ref={shell3Ref}>


      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2001.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3001.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4001.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5001.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6001.geometry}
        material={materials.Muschel_Material_u1_v1}
      />

</group>
<group ref={shell4Ref}>


      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2003.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3003.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4003.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5003.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6003.geometry}
        material={materials.Muschel_Material_u1_v1}
      />

</group>
<group ref={shell5Ref}>


      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2004.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3004.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4004.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5004.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6004.geometry}
        material={materials.Muschel_Material_u1_v1}
      />

</group>
<group ref={shell6Ref}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2005.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3005.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4005.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5005.geometry}
        material={materials.Muschel_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6005.geometry}
        material={materials.Muschel_Material_u1_v1}
      />

</group>
    </group>
  )
}

useGLTF.preload('/sea_shell_2.glb')
